# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-17 16:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='priority',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
